# docker-compose.yml

#docker rmi $(docker images -f "dangling=true" -q)
#sudo docker-compose --env-file .env up --build
version: "3"
services:
  redis:
    image: redis
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    ports:
      - "127.0.0.1:6379:6379"
    command: redis-server --bind 0.0.0.0 --requirepass ${REDIS_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "10"
    configs:
      - cfg_rpc
      - cfg_referral
      - cfg_wscfg

  # REST/WS server for frontend
  backend_main:
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - MAIN_API_PORT_HTTP=${MAIN_API_PORT_HTTP}
      - MAIN_API_PORT_WEBSOCKET=${MAIN_API_PORT_WEBSOCKET}
      - CHAIN_ID=${CHAIN_ID}
      - SDK_CONFIG_NAME=${SDK_CONFIG_NAME}
      - CORS_ON=${CORS_ON}
      - BROKER_KEY=${BROKER_KEY}
      - BROKER_FEE_TBPS=${BROKER_FEE_TBPS}
      - CONFIG_PATH_RPC=/cfg_rpc
      - CONFIG_PATH_REFERRAL_SETTINGS=/cfg_referral
      - CONFIG_PATH_WSCFG=/cfg_wscfg
    ports:
      - "127.0.0.1:${MAIN_API_PORT_WEBSOCKET}:${MAIN_API_PORT_WEBSOCKET}"
      - "127.0.0.1:${MAIN_API_PORT_HTTP}:${MAIN_API_PORT_HTTP}"
      - "8880:8880" # historyAPIEndpoint
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "5000k"
        max-file: "10"
    configs:
      - cfg_rpc
      - cfg_referral
      - cfg_wscfg

  # History component listens to block-chain events and stores them in postgres
  # Exposes a REST API
  backend_history:
    build:
      context: .
      dockerfile: ./packages/history/Dockerfile
    depends_on:
      - postgres
    environment:
      - DATABASE_DSN_HISTORY=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      - API_PORT=${HISTORY_API_PORT_HTTP}
      - SDK_CONFIG_NAME=${SDK_CONFIG_NAME}
      - CHAIN_ID=${CHAIN_ID}
      - CORS_ON=${CORS_ON}
      - CONFIG_PATH_RPC=/cfg_rpc
      - CONFIG_PATH_REFERRAL_SETTINGS=/cfg_referral
      - CONFIG_PATH_WSCFG=/cfg_wscfg
    ports:
      - "127.0.0.1:${HISTORY_API_PORT_HTTP}:${HISTORY_API_PORT_HTTP}"
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "5000k"
        max-file: "10"
    configs:
      - cfg_rpc
      - cfg_referral
      - cfg_wscfg

  # Referral component that handles referral/agency/broker/trader rebates
  # Exposes a REST API and uses the postgres DB that the history component mainly fills
  backend_referral:
    build:
      context: .
      dockerfile: ./packages/referral/Dockerfile
    depends_on:
      - postgres_referral
      - redis
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - DATABASE_DSN_REFERRAL=postgres://${POSTGRES_USER_REFERRAL}:${POSTGRES_PASSWORD_REFERRAL}@postgres_referral:5432/${POSTGRES_DB_REFERRAL}?schema=public
      - REFERRAL_API_PORT_HTTP=${REFERRAL_API_PORT_HTTP}
      - BROKER_KEY=${BROKER_KEY}
      - CHAIN_ID=${CHAIN_ID}
      - CORS_ON=${CORS_ON}
      - HISTORY_API_ENDPOINT=http://backend_history:${HISTORY_API_PORT_HTTP}
      - CONFIG_PATH_RPC=/cfg_rpc
      - CONFIG_PATH_REFERRAL_SETTINGS=/cfg_referral
      - CONFIG_PATH_WSCFG=/cfg_wscfg
    ports:
      - "127.0.0.1:${REFERRAL_API_PORT_HTTP}:${REFERRAL_API_PORT_HTTP}"
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "5000k"
        max-file: "10"
    configs:
      - cfg_rpc
      - cfg_referral
      - cfg_wscfg

  # stream oracle prices from price service (pyth 'offchain'-network)
  backend_pyth_connection:
    stdin_open: true # docker run -i
    tty: true # docker run -t
    build:
      context: .
      dockerfile: ./packages/pxws-client/Dockerfile
    links:
      - redis
    environment:
      - REDIS_URL="redis://:${REDIS_PASSWORD}@redis:6379/0"
      - MAIN_API_PORT_HTTP=${MAIN_API_PORT_HTTP}
      - MAIN_API_PORT_WEBSOCKET=${MAIN_API_PORT_WEBSOCKET}
      - CHAIN_ID=${CHAIN_ID}
      - CONFIG_PATH_RPC=/cfg_rpc
      - CONFIG_PATH_REFERRAL_SETTINGS=/cfg_referral
      - CONFIG_PATH_WSCFG=/cfg_wscfg
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "10"

    configs:
      - cfg_rpc
      - cfg_referral
      - cfg_wscfg

  # Database component required by history
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 127.0.0.1:${POSTGRES_PORT_HISTORY}:5432
    volumes:
      - pgdb:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "10"

  # Database component required by referral
  postgres_referral:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER_REFERRAL}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_REFERRAL}
      POSTGRES_DB: ${POSTGRES_DB_REFERRAL}
    ports:
      - 127.0.0.1:${POSTGRES_PORT_REFERRAL}:5432
    volumes:
      - pgdb_referral:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "10"
volumes:
  pgdb:
  pgdb_referral:
configs:
  cfg_rpc:
    file: ./config/live.rpc.json
  cfg_referral:
    file: ./config/live.referralSettings.json
  cfg_wscfg:
    file: ./config/live.wsConfig.json
