# docker-compose.yml

#docker rmi $(docker images -f "dangling=true" -q)
#sudo docker-compose --env-file .env up --build
version: "3"
services:
  # Args: none
  redis:
    image: redis
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  # REST/WS server for frontend
  backend_main:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - PORT_REST=${PORT_REST}
      - PORT_WEBSOCKET=${PORT_WEBSOCKET}
      - CHAIN_ID=${CHAIN_ID}
    ports:
      - "${PORT_WEBSOCKET}:${PORT_WEBSOCKET}"
      - "${PORT_REST}:${PORT_REST}"
    restart: on-failure

  backend_pyth_connection:
    stdin_open: true # docker run -i
    tty: true # docker run -t
    build:
      context: .
      dockerfile: ./src/indexPXWSClient/Dockerfile
    links:
      - redis
    environment:
      REDIS_URL: "redis://:${REDIS_PASSWORD}@redis:6379"
      PORT_REST: ${PORT_REST}
      PORT_WEBSOCKET: ${PORT_WEBSOCKET}
      CHAIN_ID: ${CHAIN_ID}
    restart: on-failure
