name: Build imagess

on:
  push:
    branches: [ "main" ]
env:
  container_registry: ghcr.io
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    -
      name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ${{ env.container_registry }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build and push main:latest
      uses: docker/build-push-action@v4
      with:
        context: .
        registry: ${{ env.container_registry }}
        file: ./packages/api/Dockerfile
        push: true
        tags: ${{ env.container_registry }}/${{ github.repository_owner }}/dx8-trader-main:latest
    -
        name: Build and push referral:latest
        uses: docker/build-push-action@v4
        with:
            context: .
            registry: ${{ env.container_registry }}
            file: ./packages/referral/Dockerfile
            push: true
            tags: ${{ env.container_registry }}/${{ github.repository_owner }}/dx8-trader-referral:latest
    -
        name: Build and push history:latest
        uses: docker/build-push-action@v4
        with:
            context: .
            registry: ${{ env.container_registry }}
            file: ./packages/history/Dockerfile
            push: true
            tags: ${{ env.container_registry }}/${{ github.repository_owner }}/dx8-trader-history:latest
    -
        name: Build and push pxws-client:latest
        uses: docker/build-push-action@v4
        with:
            context: .
            registry: ${{ env.container_registry }}
            file: ./packages/pxws-client/Dockerfile
            push: true
            tags: ${{ env.container_registry }}/${{ github.repository_owner }}/dx8-trader-pxws-client:latest
