name: Build imagess

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    -
      name: Login to registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.CONTAINER_REGISTRY_USER }}
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build and push main
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./packages/api/Dockerfile
        push: true
        tags: ${{ secrets.CONTAINER_REGISTRY_USER }}/main:latest
